name: Node CI

on:
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
    - name: Deploy action for GitHub Pages
      uses: peaceiris/actions-gh-pages@v2.2.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_dist
